import { create } from 'zustand';
import type { NewsArticle } from '@/types';

const ARTICLES_PER_PAGE = 10;

// This mock data simulates a pre-analyzed and cached data source from a backend,
// as described in the `Backend.md` file. The sentiment and category would be
// generated by a single Gemini API call on the server, not on the client.
// FIX: Export MOCK_ANALYZED_NEWS so it can be imported by other modules.
export const MOCK_ANALYZED_NEWS: NewsArticle[] = [
  {
    id: 'e28a9b1c',
    title: 'Bitcoin Surges Past $70,000 as Institutional Interest Peaks',
    description: 'Bitcoin has broken a key resistance level, driven by strong inflows into spot ETFs and positive macroeconomic signals. Analysts are optimistic about a continued rally.',
    source: 'Cointelegraph',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    url: 'https://cointelegraph.com/news/bitcoin-price-hits-70k',
    thumbnail: 'https://images.unsplash.com/photo-1621418359569-16319aa50d53?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bullish',
    category: 'Market Analysis',
  },
  {
    id: 'f9d8c7b6',
    title: 'Ethereum "Dencun" Upgrade Finalized, Layer-2 Fees Plummet by 90%',
    description: 'The highly anticipated Dencun upgrade has successfully been deployed on the Ethereum mainnet, introducing "proto-danksharding" to drastically reduce data fees for Layer-2 solutions.',
    source: 'Decrypt',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    url: 'https://decrypt.co/221169/ethereum-dencun-upgrade-live-layer-2-fees-plummet',
    thumbnail: 'https://images.unsplash.com/photo-1642155787336-83a8b4f63683?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bullish',
    category: 'Technology',
  },
  {
    id: 'a1b2c3d4',
    title: 'SEC Delays Decision on Spot Ethereum ETF, Citing Market Concerns',
    description: 'The U.S. Securities and Exchange Commission has once again postponed its decision on several spot Ethereum ETF applications, requesting further public comment on potential market manipulation.',
    source: 'CryptoSlate',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    url: 'https://cryptoslate.com/sec-postpones-decision-on-ethereum-etf-applications-again/',
    thumbnail: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bearish',
    category: 'Regulation',
  },
  {
    id: 'e5f6g7h8',
    title: 'Solana Ecosystem Sees Explosive Growth in DeFi and Memecoins',
    description: 'Despite recent network congestion issues, the Solana blockchain continues to attract a massive influx of users and developers, with trading volumes in its DeFi and memecoin sectors reaching all-time highs.',
    source: 'news.bitcoin.com',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), // 8 hours ago
    url: 'https://news.bitcoin.com/solana-defi-ecosystem-sees-massive-growth/',
    thumbnail: 'https://images.unsplash.com/photo-1641424233382-5674a4b13a22?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Neutral',
    category: 'Ecosystem',
  },
  {
    id: 'i9j0k1l2',
    title: 'Is the Metaverse Hype Over? Market Data Suggests a Major Cooldown',
    description: 'Virtual land sales and metaverse token prices have seen a significant downturn over the past quarter, leading experts to question the short-term viability of the metaverse concept.',
    source: 'Cointelegraph',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(), // 15 hours ago
    url: 'https://cointelegraph.com/news/metaverse-hype-cools-down-whats-next',
    thumbnail: 'https://images.unsplash.com/photo-1639401918439-3b4a28b174a2?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bearish',
    category: 'NFTs & Metaverse',
  },
  {
    id: 'm3n4o5p6',
    title: 'Chainlink Partners with Major Bank to Tokenize Real-World Assets',
    description: 'The oracle network Chainlink has announced a landmark partnership to explore the tokenization of real-world assets (RWAs), a move seen as a major step toward bridging traditional finance and DeFi.',
    source: 'Decrypt',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(), // 23 hours ago
    url: 'https://decrypt.co/115615/chainlink-real-world-asset-tokenization',
    thumbnail: 'https://images.unsplash.com/photo-1639755491104-4770d1f7c1d3?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bullish',
    category: 'DeFi',
  },
  {
    id: 'q7r8s9t0',
    title: 'US Inflation Data Comes in Hotter Than Expected, Crypto Markets Dip',
    description: 'The latest Consumer Price Index (CPI) report showed inflation remaining persistent, leading to a risk-off sentiment across markets, with Bitcoin and major altcoins seeing a sharp correction.',
    source: 'CryptoSlate',
    timestamp: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    url: 'https://cryptoslate.com/cpi-data-impacts-crypto-markets/',
    thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Bearish',
    category: 'Macro',
  },
  {
    id: 'u1v2w3x4',
    title: 'How AI is Changing the Game for Crypto Trading Bots',
    description: 'New developments in artificial intelligence are allowing trading bots to move beyond simple arbitrage strategies, employing predictive analytics to navigate complex market conditions.',
    source: 'Cointelegraph',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(), // 2 days ago
    url: 'https://cointelegraph.com/news/ai-crypto-trading-bots-evolution',
    thumbnail: 'https://images.unsplash.com/photo-1677756119517-756a188d2d94?q=80&w=1920&auto-format&fit=crop',
    sentiment: 'Neutral',
    category: 'Technology',
  },
   {
    id: 'y5z6a7b8',
    title: 'Gaming Giant Announces Integration with Polygon for In-Game NFTs',
    description: 'A major player in the video game industry has revealed plans to use the Polygon network for its upcoming NFT marketplace, aiming for low fees and fast transaction times.',
    source: 'Decrypt',
    timestamp: new Date(Date.now() - 86400000 * 2.5).toISOString(),
    url: 'https://decrypt.co/110111/gaming-giant-polygon-nft-marketplace',
    sentiment: 'Bullish',
    category: 'Gaming & NFTs',
  },
  {
    id: 'c9d0e1f2',
    title: 'Binance Faces Regulatory Scrutiny in New Jurisdiction',
    description: 'The world\'s largest crypto exchange is under investigation by financial regulators in another country, adding to its ongoing global legal challenges.',
    source: 'CryptoSlate',
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    url: 'https://cryptoslate.com/binance-regulatory-issues-continue/',
    sentiment: 'Bearish',
    category: 'Regulation',
  },
  {
    id: 'g3h4i5j6',
    title: 'The Rise of Restaking: Is It the Next Big DeFi Narrative?',
    description: 'Protocols like EigenLayer are pioneering the concept of "restaking," allowing users to secure multiple networks with their staked ETH and earn additional rewards, but it comes with new risks.',
    source: 'Cointelegraph',
    timestamp: new Date(Date.now() - 86400000 * 3.2).toISOString(),
    url: 'https://cointelegraph.com/news/what-is-restaking-defi-explained',
    sentiment: 'Neutral',
    category: 'DeFi',
  },
  {
    id: 'k7l8m9n0',
    title: 'Central Bank Digital Currencies (CBDCs): A Threat to Crypto?',
    description: 'As more governments explore CBDCs, the crypto community debates whether they represent a threat to decentralized currencies or a bridge for mainstream adoption.',
    source: 'news.bitcoin.com',
    timestamp: new Date(Date.now() - 86400000 * 4).toISOString(),
    url: 'https://news.bitcoin.com/cbdcs-friend-or-foe-to-crypto/',
    sentiment: 'Neutral',
    category: 'Macro',
  },
];

interface NewsState {
  allArticles: NewsArticle[];
  displayedArticles: NewsArticle[];
  isLoading: boolean;
  isAppending: boolean;
  error: string | null;
  hasMore: boolean;
  fetchNews: () => Promise<void>;
  loadMoreNews: () => void;
}

export const useNewsStore = create<NewsState>((set, get) => ({
  allArticles: [],
  displayedArticles: [],
  isLoading: false,
  isAppending: false,
  error: null,
  hasMore: true,

  fetchNews: async () => {
    if (get().allArticles.length > 0) {
      set({ isLoading: false });
      return;
    }
    
    set({ isLoading: true, error: null });

    try {
      // Simulate fetching pre-analyzed data from a backend service.
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      const fetchedArticles = MOCK_ANALYZED_NEWS;

      // The backend would have already sorted them, but we do it here just in case.
      fetchedArticles.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
      
      set({
        allArticles: fetchedArticles,
        displayedArticles: fetchedArticles.slice(0, ARTICLES_PER_PAGE),
        hasMore: fetchedArticles.length > ARTICLES_PER_PAGE,
        isLoading: false,
      });

    } catch (e) {
      const error = e instanceof Error ? e.message : 'Failed to fetch market news from the server.';
      set({ error, isLoading: false, allArticles: [], displayedArticles: [] });
      console.error(e);
    }
  },
  
  loadMoreNews: () => {
    set({ isAppending: true });
    // Simulate a small delay for loading more articles
    setTimeout(() => {
        const { allArticles, displayedArticles } = get();
        const currentCount = displayedArticles.length;
        const nextCount = currentCount + ARTICLES_PER_PAGE;
        
        const newArticles = allArticles.slice(0, nextCount);

        set({
            displayedArticles: newArticles,
            hasMore: newArticles.length < allArticles.length,
            isAppending: false,
        });
    }, 500);
  }
}));